server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: access_control_system
  profiles:
    # 复制 application-dev.yml文件，新建一个文件名为 application-test.yml 修改数据库信息连接信息为自己的连接信息
    active: test
  # 解决knife4j接口文档异常：Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    driver-class-name: ${accesscontrol.datasource.driver-class-name}
    url: ${accesscontrol.datasource.url}
    username: ${accesscontrol.datasource.username}
    password: ${accesscontrol.datasource.password}


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
